
framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false

    session:
        handler_id: 'App\Session\CookieSessionHandler'

    php_errors:
        log: true

when@test:
    framework:
        test: true
