parameters:
    akeneoClientId: '%env(string:AKENEO_CLIENT_ID)%'

services:
    _defaults:
        public: true

    Symfony\Component\HttpClient\MockHttpClient: ~

    Symfony\Contracts\HttpClient\HttpClientInterface: '@Symfony\Component\HttpClient\MockHttpClient'

    test.App\Storage\AccessTokenSessionStorage: '@App\Storage\AccessTokenSessionStorage'
    test.App\Storage\PimURLStorageInterface: '@App\Storage\PimURLStorageInterface'

    App\Service\DnsLookupInterface:
        class: 'App\Tests\Mock\FakeDnsLookup'
