services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $akeneoClientId: '%env(string:AKENEO_CLIENT_ID)%'
            $akeneoClientSecret: '%env(string:AKENEO_CLIENT_SECRET)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/Controller/'
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/**/*Action.php'
        tags:
            - { name: 'controller.service_arguments' }

    Symfony\Component\HttpClient\Psr18Client: ~

    App\PimApi\PimApiClientFactory:
        arguments:
            $httpClient: '@Symfony\Component\HttpClient\Psr18Client'

    Akeneo\Pim\ApiClient\AkeneoPimClientInterface:
        class: 'Akeneo\Pim\ApiClient\AkeneoPimClientInterface'
        factory: '@App\PimApi\PimApiClientFactory'
