services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $akeneoClientId: '%env(string:AKENEO_CLIENT_ID)%'
            $akeneoClientSecret: '%env(string:AKENEO_CLIENT_SECRET)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/Controller/'
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/**/*Action.php'
        tags:
            - { name: 'controller.service_arguments' }

    Akeneo\Pim\ApiClient\AkeneoPimClientInterface:
        class: 'Akeneo\Pim\ApiClient\AkeneoPimClientInterface'
        factory: '@App\PimApi\Client\PimApiClientFactory'
